# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1d98475e98992dc47646e4f2ab50036e47b42f677b5f762a58b7a60f8e96e446883e724bb855b680b1a4cc83a69092aab0d410d108ae42654bf3ac8b2e974ee2

test:
  secret_key_base: 0719a471f226a6f74266f9e1244b6c4e24f6fdc87915a2369a4bd2f092c777e357cc86b0df209ab675e4eeda7b9d397540e04d73c7197cbc734d372512e2f18a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
